### ISSUE TITLE
User can add a habit

### ISSUE THREAD

**Issue by cgmccanna** [cgmccanna/habit-tracker#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add a habit
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can input information about a new habit they want to start tracking, and it will be added to their list of habits
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2023-06-06 210108](https://github.com/cgmccanna/habit-tracker/assets/74582871/0ba6a662-b178-4bc1-8da5-f0cd547b672c)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [ ] Update `schema.sql` to create 4 tables
- [ ] Update `data.sql` to insert mock data

### ☁️ Server Tasks

- [ ] Update `server.js` to handle get requests
    - [ ] select habit titles from db and map them
- [ ] Update `server.js` to handle post requests
    - [ ] insert habit data into db
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client Tasks

- [ ] Create a form component to allow user to input habit title, description, frequency, location
- [ ] Create a component to display list of habits that user has input

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] Style components with CSS
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
